spring:
  application:
    name: test-app
  mail:
    host: smtp.gmail.com
    username: olojedechristopher24@gmail.com
    password: uapoewtxdaxrarqe
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com
          auth: true
